Repository trento-project/trento, pull requests merged in 2021-11, with the labels that each got.

#402 Store checks metadata in the DB instead of ARA
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  runner/ansible/meta.yml
  runner/ansible/roles/post-metadata/tasks/post.yml
  runner/ansible/roles/post-metadata/tasks/store.yml
  runner/ansiblerunner.go
  runner/runner.go
  runner/runner_test.go
  web/app.go
  web/checks_api.go
  web/checks_api_test.go
  web/checks_catalog_test.go
  web/clusters_test.go
  web/models/check.go
  web/models/check_test.go
  web/services/checks.go
  web/services/checks_mock.go
  web/services/checks_test.go
Labels: enhancement

#406 fix CI issues
  .github/workflows/ci-cd.yaml
  requirements.dev.txt
Labels: DX

#411 Update Swagger usage
  Makefile
  docs/api/README.md
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  go.mod
  go.sum
  web/api.go
  web/api_test.go
  web/app.go
Labels: documentation, DX

#417 Fix cloud os user name retrieval in the runner side
  runner/inventory.go
  runner/inventory_test.go
Labels: bug

#413 Makefile updates
  Makefile
Labels: DX

#418 Project telemetry data
  agent/discovery/collector/client_test.go
  agent/discovery/collector/publishing_test.go
  agent/discovery/host.go
  agent/discovery/mocks/discovered_cloud_mock.go
  agent/discovery/mocks/discovered_cluster_mock.go
  agent/discovery/mocks/discovered_host_mock.go
  agent/discovery/mocks/discovered_subscription_mock.go
  internal/hosts/discovered_host.go
  test/fixtures/discovery/host/expected_published_host_discovery.json
  test/testing.go
  web/app.go
  web/datapipeline/clusters_projector_test.go
  web/datapipeline/data_collected_event.go
  web/datapipeline/host_telemetry_projector.go
  web/datapipeline/host_telemetry_projector_test.go
  web/datapipeline/projector_registry.go
  web/models/host_telemetry.go
Labels: enhancement

#426 Add host health aggregation matrix to the dev notes
  docs/development/health-aggregation-matrix.md
Labels: documentation

#457 Remove /api prefix from swagger api docstrings
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  web/checks_api.go
  web/tags_api.go
Labels: bug

#468 Pin pyparsing to ~2.0 version to avoid issues in runner container
  Dockerfile
Labels: bug

#466 Detect aws and gcp clouds in the agent
  internal/cloud/metadata.go
  internal/cloud/metadata_test.go
Labels: enhancement

#470 Include the consul-config-dir init in the agent install script
  install-agent.sh
Labels: bug

#471 Added scrollbars to the codeblocks
  web/frontend/stylesheets/stylesheets.scss
Labels: bug

#440 Split the runner environment vars in directories
  runner/ansible/roles/load_facts/tasks/main.yml
  runner/ansible/vars/azure/10-default.yml
  runner/ansible/vars/dev/10-default.yml
Labels: enhancement

#461 Migrate about page and sles subscriptions data to the database
  agent/agent.go
  agent/discovery/subscription.go
  internal/subscription/subscription_kvstore.go
  internal/subscription/subscription_kvstore_test.go
  web/about.go
  web/about_test.go
  web/app.go
  web/datapipeline/projector_registry.go
  web/datapipeline/sles_subsciptions_projector.go
  web/datapipeline/sles_subsciptions_projector_test.go
  web/entities/host.go
  web/entities/sles_subscription.go
  web/hosts_test.go
  web/models/sles_subscription.go
  web/services/subscriptions.go
  web/services/subscriptions_mock.go
  web/services/subscriptions_test.go
  web/templates/about.html.tmpl
  web/templates/host.html.tmpl
Labels: enhancement, debt

#509 Move checks structs to entities and remove old checks in catalog
  web/app.go
  web/entities/check.go
  web/models/check.go
  web/services/checks.go
  web/services/checks_test.go
Labels: DX
