Repository trento-project/trento, pull requests merged in 2021-12, with the labels that each got.

#525 Show HANA details in its details page
  web/templates/sapsystem.html.tmpl
Labels: bug

#526 Create properly the SAP system url in the host page
  web/hosts_test.go
  web/templates/host.html.tmpl
Labels: bug

#519 Improve changes file generation
  .github/workflows/ci-cd.yaml
  hack/gh_release_to_obs_changeset.py
Labels: DX

#527 Show SAP instance number using 2 digits
  web/sapsystems_test.go
  web/templates/blocks/sapsystem_layout.html.tmpl
Labels: bug

#530 Add live logging ansible
  runner/ansiblerunner.go
Labels: enhancement, DX

#534 Set a timeout in ansible tasks
  packaging/helm/trento-server/Chart.yaml
  packaging/helm/trento-server/charts/trento-runner/Chart.yaml
  packaging/helm/trento-server/charts/trento-runner/templates/deployment.yaml
  runner/ansible/callback_plugins/trento.py
  runner/ansible/check.yml
  runner/inventory.go
  web/checks_api_test.go
  web/frontend/components/ChecksTable/RowGroup.js
  web/models/check.go
  web/services/checks_test.go
Labels: bug

#561 Refactor cluster settings fe
  api/api.go
  api/checks.go
  api/checks_test.go
  api/mocks/TrentoApiService.go
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  web/app.go
  web/checks_api.go
  web/checks_api_test.go
  web/clusters.go
  web/frontend/javascripts/cluster_check_settings.js
  web/services/clusters.go
  web/services/clusters_mock.go
  web/services/clusters_test.go
  web/services/hosts_consul.go
  web/services/hosts_consul_mock.go
  web/services/hosts_consul_test.go
Labels: enhancement, api, debt

#559 Cleanup agent from consul
  agent/agent.go
  agent/consultemplate.go
  agent/discovery/cloud.go
  agent/discovery/cluster.go
  agent/discovery/discovery.go
  agent/discovery/host.go
  agent/discovery/sapsystem.go
  agent/discovery/sapsystem_test.go
  agent/discovery/subscription.go
  cmd/agent/config.go
  go.mod
  go.sum
  install-agent.sh
  packaging/config/agent.yaml
  packaging/systemd/trento-agent.service
Labels: enhancement, debt

#560 Clean up helm chart form consul references
  ct.yaml
  hack/deploy.sh
  hack/helm/trento-dev/Chart.lock
  packaging/helm/trento-server/Chart.lock
  packaging/helm/trento-server/Chart.yaml
  packaging/helm/trento-server/charts/trento-runner/templates/deployment.yaml
  packaging/helm/trento-server/charts/trento-runner/values.yaml
  packaging/helm/trento-server/charts/trento-web/templates/deployment.yaml
  packaging/helm/trento-server/charts/trento-web/values.yaml
  packaging/helm/trento-server/values.yaml
Labels: dependencies, installation, debt

#562 Remove consul references from the README
  README.md
Labels: documentation, installation, debt

#500 Remove premium checks and their variables
  runner/ansible/roles/checks/1.1.10/defaults/main.yml
  runner/ansible/roles/checks/1.1.10/tasks/main.yml
  runner/ansible/roles/checks/1.4.1/defaults/main.yml
  runner/ansible/roles/checks/1.4.1/tasks/main.yml
  runner/ansible/roles/checks/1.4.2/defaults/main.yml
  runner/ansible/roles/checks/1.4.2/tasks/main.yml
  runner/ansible/roles/checks/1.5.1/defaults/main.yml
  runner/ansible/roles/checks/1.5.1/tasks/main.yml
  runner/ansible/roles/checks/2.1.1/defaults/main.yml
  runner/ansible/roles/checks/2.1.1/tasks/main.yml
  runner/ansible/roles/checks/2.1.2/defaults/main.yml
  runner/ansible/roles/checks/2.1.2/tasks/main.yml
  runner/ansible/roles/checks/2.1.3/defaults/main.yml
  runner/ansible/roles/checks/2.1.3/tasks/main.yml
  runner/ansible/roles/checks/2.1.4/defaults/main.yml
  runner/ansible/roles/checks/2.1.4/tasks/main.yml
  runner/ansible/roles/checks/2.1.5/defaults/main.yml
  runner/ansible/roles/checks/2.1.5/tasks/main.yml
  runner/ansible/roles/checks/2.1.6/defaults/main.yml
  runner/ansible/roles/checks/2.1.6/tasks/main.yml
  runner/ansible/roles/checks/2.1.7/defaults/main.yml
  runner/ansible/roles/checks/2.1.7/tasks/main.yml
  runner/ansible/roles/checks/2.1.8/defaults/main.yml
  runner/ansible/roles/checks/2.1.8/tasks/main.yml
  runner/ansible/roles/checks/2.2.10/defaults/main.yml
  runner/ansible/roles/checks/2.2.10/tasks/main.yml
  runner/ansible/roles/checks/2.2.6/defaults/main.yml
  runner/ansible/roles/checks/2.2.6/tasks/main.yml
  runner/ansible/roles/checks/2.2.8/defaults/main.yml
  runner/ansible/roles/checks/2.2.8/tasks/main.yml
  runner/ansible/roles/checks/2.2.9/defaults/main.yml
  runner/ansible/roles/checks/2.2.9/tasks/main.yml
  runner/ansible/vars/azure/10-default.yml
  runner/ansible/vars/dev/10-default.yml
Labels: removal

#587 Fix SBD checks 0B6DB2 and 49591F remediation rendering
  runner/ansible/roles/checks/1.3.1/defaults/main.yml
  runner/ansible/roles/checks/1.3.2/defaults/main.yml
Labels: bug

#592 fix bogus docker build makefile error
  Dockerfile
  hack/helm/trento-dev/Chart.lock
Labels: bug

#628 Align properly the cluster sites tables columns
  web/clusters_test.go
  web/frontend/stylesheets/stylesheets.scss
  web/templates/blocks/sites.html.tmpl
Labels: bug

#639 Fix test 373DB8 to pass if timeout unit is set
  runner/ansible/roles/checks/1.2.2/tasks/main.yml
Labels: bug

#654 Create the premium detecion service mocks properly
  web/middlewares_test.go
  web/services/checks_test.go
  web/services/clusters_test.go
  web/services/premium_detection.go
  web/services/premium_detection_mock.go
  web/telemetry/engine_test.go
  web/web_test.go
Labels: bug

#652 Store runner check results in the database
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  runner/ansible/callback_plugins/trento.py
  runner/ansible/check.yml
  web/app.go
  web/checks_api.go
  web/checks_api_test.go
  web/entities/check_result.go
  web/models/check.go
  web/models/check_result.go
  web/services/checks.go
  web/services/checks_mock.go
  web/services/checks_test.go
  web/services/clusters_test.go
Labels: enhancement
