Repository trento-project/trento, pull requests merged in 2021-10, with the labels that each got.

#296 Remove docker-compose.yml
  docker-compose.yml
Labels: removed

#302 Fetch tags before building container images
  .github/workflows/ci-cd.yaml
Labels: bug

#291 Cluster health details view makeover
  Makefile
  web/api.go
  web/app.go
  web/clusters_test.go
  web/frontend/.babelrc
  web/frontend/.eslintrc.js
  web/frontend/components/Accordion/Accordion.js
  web/frontend/components/Accordion/index.js
  web/frontend/components/ChecksTable/CheckResultIcon.js
  web/frontend/components/ChecksTable/ChecksTable.js
  web/frontend/components/ChecksTable/index.js
  web/frontend/javascripts/check_results.js
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/stylesheets/stylesheets.scss
  web/frontend/webpack.config.js
  web/layout.go
  web/models/check.go
  web/templates/blocks/cluster_checks_result_modal.html.tmpl
  web/templates/cluster_hana.html.tmpl
Labels: enhancement

#303 Add hana database entry sidebar
  agent/discovery/sapsystem.go
  agent/discovery/sapsystem_test.go
  internal/hosts/metadata.go
  internal/sapsystem/sapsystem.go
  internal/sapsystem/sapsystem_test.go
  web/app.go
  web/hosts_test.go
  web/sap_systems_test.go
  web/sapsystems.go
  web/sapsystems_test.go
  web/services/hosts.go
  web/services/hosts_test.go
  web/services/mocks/HostsService.go
  web/services/mocks/SAPSystemsService.go
  web/services/sapsystems.go
  web/services/sapsystems_test.go
  web/templates/blocks/hosts_table.html.tmpl
  web/templates/blocks/sap_system_layout.html.tmpl
  web/templates/blocks/sapsystem_layout.html.tmpl
  web/templates/blocks/sapsystems_table.html.tmpl
  web/templates/blocks/sidebar.html.tmpl
  web/templates/sapsystem.html.tmpl
  web/templates/sapsystems.html.tmpl
Labels: enhancement

#306 Add PostgreSQL
  .github/workflows/ci-cd.yaml
  .gitignore
  README.md
  cmd/root.go
  cmd/web/web.go
  go.mod
  go.sum
  hack/helm/trento-dev/Chart.lock
  hack/helm/trento-dev/Chart.yaml
  hack/helm/trento-dev/values.yaml
  internal/hosts/hosts.go
  internal/hosts/hosts_test.go
  internal/tags/tags.go
  internal/tags/tags_test.go
  packaging/helm/trento-server/Chart.lock
  packaging/helm/trento-server/Chart.yaml
  packaging/helm/trento-server/charts/trento-web/templates/deployment.yaml
  packaging/helm/trento-server/values.yaml
  web/about_test.go
  web/api.go
  web/api_test.go
  web/app.go
  web/checks_catalog_test.go
  web/clusters.go
  web/clusters_test.go
  web/home_test.go
  web/hosts.go
  web/hosts_test.go
  web/models/tag.go
  web/sapsystems.go
  web/sapsystems_test.go
  web/services/hosts.go
  web/services/mocks/TagsService.go
  web/services/sapsystems.go
  web/services/services_test.go
  web/services/tags.go
  web/services/tags_test.go
  web/web_test.go
Labels: enhancement
