Repository trento-project/trento, pull requests merged in 2022-02, with the labels that each got.

#750 Add e2e tests for hana database details page
  test/e2e/cypress/fixtures/.photofinish.toml
  test/e2e/cypress/fixtures/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_GRAY.json
  test/e2e/cypress/fixtures/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_GREEN.json
  test/e2e/cypress/fixtures/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_RED.json
  test/e2e/cypress/fixtures/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_YELLOW.json
  test/e2e/cypress/fixtures/hana-database-details/hana_database_details.feature
  test/e2e/cypress/fixtures/hana-database-details/newagent_sap_system_discovery_new.json
  test/e2e/cypress/fixtures/hana-database-details/selected_database.js
  test/e2e/cypress/integration/hana_database_details.js
Labels: enhancement

#779 Prometheus HTTP service discovery API
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  web/app.go
  web/models/prometheus.go
  web/prometheus_api.go
  web/prometheus_api_test.go
  web/services/prometheus.go
  web/services/prometheus_mock.go
  web/services/prometheus_test.go
Labels: enhancement

#749 CI: add install-helm-charts job
  .github/workflows/ci-cd.yaml
Labels: enhancement, DX

#807 Sap system health computation
  test/e2e/cypress/fixtures/.photofinish.toml
  test/e2e/cypress/fixtures/sap-systems-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery_RED.json
  test/e2e/cypress/fixtures/sap-systems-overview/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_RED.json
  test/e2e/cypress/fixtures/sap-systems-overview/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery_GRAY.json
  test/e2e/cypress/fixtures/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_YELLOW.json
  test/e2e/cypress/fixtures/sap-systems-overview/available_sap_systems.js
  test/e2e/cypress/fixtures/sap-systems-overview/sap_systems_overview.feature
  test/e2e/cypress/integration/sap_systems_overview.js
  web/models/sap_system.go
  web/services/sap_systems.go
  web/services/sap_systems_test.go
  web/templates/blocks/sap_systems_table.html.tmpl
Labels: enhancement

#824 Compute attached database health
  web/services/sap_systems.go
  web/services/sap_systems_test.go
Labels: bug

#828 Use context correctly during db initialization
  cmd/ctl/ctl.go
  cmd/web/web.go
  internal/db/db.go
  test/helpers/db.go
  web/app.go
Labels: bug

#782 Add node exporter state in the frontend
  .github/workflows/ci-cd.yaml
  cmd/web/config.go
  cmd/web/config_test.go
  cmd/web/web.go
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  go.mod
  go.sum
  hack/helm/trento-dev/Chart.lock
  internal/prometheus/prometheus.go
  internal/prometheus/prometheus_mock.go
  packaging/helm/trento-server/Chart.yaml
  packaging/helm/trento-server/charts/trento-web/Chart.yaml
  packaging/helm/trento-server/charts/trento-web/templates/deployment.yaml
  packaging/helm/trento-server/charts/trento-web/values.yaml
  packaging/helm/trento-server/values.yaml
  test/fixtures/config/web.yaml
  web/app.go
  web/hosts.go
  web/hosts_test.go
  web/services/hosts.go
  web/services/hosts_mock.go
  web/services/hosts_test.go
  web/services/prometheus.go
  web/services/prometheus_mock.go
  web/services/prometheus_test.go
  web/templates/host.html.tmpl
Labels: enhancement
